### ISSUE TITLE
Measurement tools do not work due to changes to setup_process()

### ISSUE THREAD

**Issue by edbennett** [claudiopica/HiRep#1]
The centralised implementation of `read_cmdline()` (seemingly introduced in https://github.com/claudiopica/HiRep/commit/7ffaeea3e685770260dd1ea4481cd5e82b4d0a1c) doesn't work with the spectroscopy and other measurement codes. Initially these fail to compile because `setup_process()` is now declared `static`. After adjusting this to be not static, the programs compile, but one is required to use `-c` or `-l` to specify a configuration or list file—however, this argument is then rejected by the central `read_cmdline()`, which only expects `-i` and `-o`. Similarly, `converter` fails because it expects the parameter passed to `-i` to be a configuration rather than a text input file.

I can see three ways of approaching a fix:

1. Revert the changes that caused this to break, moving `read_cmdline()` back to `hmc`
2. Add a flag to `setup_process()` that controls whether `read_cmdline()` is called there or if it is skipped and left to the individual application to handle this.
3. Modify `setup_process()` and `read_cmdline` to take a struct of settings for the command line, and incorporate all of the setup currently done in the individual applications into `process_init.c`.

Which of these (if any) would be preferable? Thanks!

**Comment by edbennett** [comment]
(I've just noticed this only applies to the HiRep-COMP branch, not the master branch, in case that is relevant.)

**Comment by rabdomant** [comment]
Hi Ed, yes at the moment the only definitive implementations of a main code  are hmc and pure_gauge.
We are working on the other mains (but with low priority).
The issue is only related to HiRep-COMP as it is the main development branch at the moment.
I would say that none of the options you suggest for the fix are ideal and I would probably suggest to move into an input file all the options presently passed through the command line.
Regards
A.

**Comment by rabdomant** [comment]
On a secondo thought I have released the constraint on the number of input option.
You can now add additional options to the command line (as long as they are not -i -o or -m).
Regards
A.
