### ISSUE TITLE
should a LICENSE file be added?

### ISSUE THREAD

**Issue by edbennett** [claudiopica/HiRep#3]
HiRep includes and directly links against Martin Lüscher's RANLUX, which is licensed under GPLv2. In principle this should mean that HiRep is also GPLv2 licensed, and is required to state as much in the distribution.

Should a COPYING or LICENSE file be added to the root of the repository (in all branches) containing a copy of the GPL v2?

**Comment by claudiopica** [comment]
I'll add a LICENSE in the main branch. This should be enough for now. The code is now under rework, and many branches are also inactive.
