### ISSUE TITLE
-DMEASURE_FORCE is broken

### ISSUE THREAD

**Issue by edbennett** [claudiopica/HiRep#5]
When compiling `hmc` with `MACRO += -DMEASURE_FORCE` defined in `MkFlags`, the compiler gives the following error:

```
Compiling [%/LibHR/Update/force0.o]...force0.c:80:17: error: use of undeclared identifier 'beta'
  forcestat0 *= beta / ((4. * NG) * GLB_VOLUME);
                ^
force0.c:81:17: error: use of undeclared identifier 'beta'
  forcestat1 *= beta / ((double)(NG));
                ^
2 errors generated.
  FAIL
```

**Comment by edbennett** [comment]
Fixing this relatively trivial problem surfaces a second:

```
Compiling [%/LibHR/Update/update_mt.o]...update_mt.c:390:8: error: no member named 'init_traj' in 'struct _monomial'
    m->init_traj(m);
    ~  ^
update_mt.c:427:12: error: no member named 'force_f' in 'struct _monomial'
        m->force_f(1, m->force_par);
        ~  ^
2 errors generated.
  FAIL
```

This one seems a little less trivial to fix.

**Comment by edbennett** [comment]
The latter of these errors is fixed by replacing `force_f` by `update_force`. I'm still not sure about the first, although I haven't spent a huge amount of time on it; commenting out the function body allows the code to compile and correctly display the gauge force.

**Comment by claudiopica** [comment]
Hi @edbennett ! we're in the process of a general cleanup and upgrade of the code. We're aware of this issue and we plan to re-write the code for measuring forces in the near future. I'm closing this issue now.
